FROM python:3.8

WORKDIR /app

RUN pip install poetry

ADD pyproject.toml .
ADD poetry.lock .

RUN poetry config virtualenvs.create false && poetry install

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
